

FROM alpine:latest
RUN apk update
RUN apk add py-pip
RUN apk add --no-cache python3-dev 
RUN pip install --upgrade pip
WORKDIR /app
COPY . /app
RUN pip --no-cache-dir install -r requirements.txt
ARG SECRET_KEY
ARG MOVIE_DATABASE_USERNAME
ARG MOVIE_DATABASE_PASSWORD
ARG MOVIE_DATABASE_URL
ENV SECRET_KEY="super secret guy" 
ENV MOVIE_DATABASE_USERNAME="neo4j" 
ENV MOVIE_DATABASE_PASSWORD="probe-tears-independence"
ENV MOVIE_DATABASE_URL="bolt://18.214.39.110:7687"
CMD ["python3", "app.py"]
